# Project
version=21.3
group=net.darkhax.attributefix
java_version=21

# Mod
mod_name=AttributeFix
mod_author=Darkhax
mod_id=attributefix
mod_license=LGPL 2.1
mod_description=Extends the maximum attribute ranges to allow for higher values.
mod_repo=https://github.com/Darkhax-Minecraft/AttributeFix
mod_docs=https://docs.darkhax.net/mods/attributefix/
mod_item_icon=minecraft:egg

# Build Flags
mod_client_only=false

# Common
minecraft_version=1.21.3
minecraft_version_range=[1.21.3, 1.22)
neo_form_version=1.21.3-20241023.131943
parchment_minecraft=1.21.3
parchment_version=2024.12.07
prickle_version=21.3.1

# NeoForge
neoforge_version=21.3.90
neoforge_loader_version_range=[4,)

# Fabric
fabric_version=0.114.1+1.21.3
fabric_loader_version=0.17.2

# CurseForge
curse_project=280510
curse_page=https://www.curseforge.com/minecraft/mc-mods/attributefix

# Modrinth
modrinth_project=lOOpEntO
modrinth_page=https://modrinth.com/mod/attributefix

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false