modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/AttributeFix/issues"
license="LGPL v2.1"

[[mods]]
modId="attributefix"
updateJSONURL="https://updates.blamejared.com/get?n=attributefix&gv=1.18.1"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="Darkhax"
description='''
${mod_description}
'''

[[dependencies.attributefix]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.attributefix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="SERVER"