modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Darkhax-Minecraft/AttributeFix/issues"
license="LGPL v2.1"

[[mods]]
modId="attributefix"
updateJSONURL="https://updates.blamejared.com/get?n=attributefix&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.attributefix]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.attributefix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="SERVER"