modLoader = "javafml"
license = "LGPL 2.1"
issueTrackerURL = "https://github.com/Darkhax-Minecraft/AttributeFix/issues"

[[mods]]
modId = "attributefix"
version = "26.2.0.0"
displayName = "AttributeFix"
updateJSONURL = "https://updates.blamejared.com/get?n=attributefix&gv=26.2&ml=neoforge"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/attributefix"
logoFile = "logo_attributefix.png"
logoBlur = false
credits = "This project is made possible with Patreon support from players like you. Thank you! lothrazar, techsquirrel, Keyana , Darkosto, Tobias Ward, noobanidus"
authors = "Darkhax"
description = "Extends the maximum attribute ranges to allow for higher values."

[[mixins]]
config = "attributefix.common.mixins.json"

[[mixins]]
config = "attributefix.neoforge.mixins.json"

[[dependencies.attributefix]]
modId = "minecraft"
type = "required"
versionRange = "26.2"
ordering = "NONE"
side = "BOTH"

[[dependencies.attributefix]]
modId = "neoforge"
type = "required"
versionRange = "[26.2.0.1-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.attributefix]]
modId = "prickle"
type = "required"
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

